version:  '3.8'
services:
    mysql:
        container_name: senderino_mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    nginx:
        container_name: senderino_nginx
        image: nginx:latest
        volumes:
            - './apps/backend/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php
    redis:
        container_name: senderino_redis
        image: redis:latest
    rabbitmq:
        container_name: senderino_rabbitmq
        image: rabbitmq:management
        ports:
            - '${RABBITMQ_MNGT_PORT}:15672'
    php:
        container_name: senderino_backend
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './apps/backend/:/usr/src/app'
        links:
            - mysql
            - rabbitmq
            - redis
        env_file:
            - .env
        environment:
            TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
            TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
            TWILIO_NUMBER: ${TWILIO_NUMBER}

# DEV NOTE
# Use a docker-compose.override.yml file for production
